### ISSUE TITLE
Cannot use Xabbuh\XApi\Model\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by djoudi** [php-xapi/client#27] opened 2018-04-15 14:23 UTC
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Cannot use Xabbuh\XApi\Model\Object as Object because 'Object' is a special class name

vendor\php-xapi\symfony-serializer\src\Normalizer\ObjectNormalizer.php
<?php
 
/*
 * This file is part of the xAPI package.
 *
 * (c) Christian Flothmann <christian.flothmann@xabbuh.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
 
namespace Xabbuh\XApi\Serializer\Symfony\Normalizer;
 
use Xabbuh\XApi\Model\Activity;
use Xabbuh\XApi\Model\IRI;
use Xabbuh\XApi\Model\Object;
use Xabbuh\XApi\Model\Statement;
use Xabbuh\XApi\Model\StatementId;
use Xabbuh\XApi\Model\StatementReference;
use Xabbuh\XApi\Model\SubStatement;
 
/**
 * Normalizes and denormalizes xAPI statement objects.
 *
 * @author Christian Flothmann <christian.flothmann@xabbuh.de>
 */
final class ObjectNormalizer extends Normalizer
{
    /**
     * {@inheritdoc}
     */
    public function normalize($object, $format = null, array $context = array())
    {
        if ($object instanceof Activity) {
            $activityData = array(
                'objectType' => 'Activity',
                'id' => $object->getId()->getValue(),
            );
 
            if (null !== $definition = $object->getDefinition()) {
Arguments
"Cannot use Xabbuh\XApi\Model\Object as Object because 'Object' is a special class name"

**Comment by djoudi** [comment] 2018-04-15 15:58
@xabbuh

**Comment by coder-sukanta** [comment] 2019-03-14 19:00
@xabbuh is this issue fixed in current version?
I am also getting this error.

**Comment by xabbuh** [comment] 2019-03-14 21:54
Can you confirm that using `^0.6@dev` solves the issue? If that's the case, I will just need to tag new releases.

**Comment by coder-sukanta** [comment] 2019-03-14 22:14
Hi, I was facing the issue Installation request for php-xapi/client ^0.5.0 -> satisfiable by php-xapi/client[v0.5.0] while installing through composer. So i downloaded codebase in my local directory and executed composer install to update all the dependencies within client-master directory.
Then changed composer.json file of this library (added Version as dev).

After that i added it as repositories in my lumen composer.json file and execute composer require php-xapi/client @dev,composer dumpautoload from my lumen root directory. 

I am attaching both the composer file here please have a look.

[Composer(Client Master).txt](https://github.com/php-xapi/client/files/2968687/Composer.Client.Master.txt)


[composer (Lumen).txt](https://github.com/php-xapi/client/files/2968688/composer.copy.txt)

**Comment by xabbuh** [comment] 2019-03-16 10:47
I have just tagged the 0.6.0 release. Can you confirm that this release fixes your issue?

**Comment by xabbuh** [comment] 2019-03-20 15:51
Please comment if the issue isn't resolved for you, closing here for now. Thank you for understanding!

**Closed by xabbuh** 2019-03-20 15:51 UTC
